/**
 * ArenaMind — Shared TypeScript type definitions
 *
 * Central type definitions used across the backend: agents, simulator, API, and database.
 * All public interfaces are exported and documented.
 */

// ─── Simulator Types ────────────────────────────────────────────────────────────

/** Types of telemetry events emitted by the simulator */
export type TelemetryType =
  | 'turnstile_count'
  | 'queue_length'
  | 'restroom_occupancy'
  | 'temp_weather'
  | 'medical_alert'
  | 'gate_status';

/** A single telemetry event from the synthetic data simulator */
export interface TelemetryEvent {
  timestamp: string;
  zone_id: string;
  type: TelemetryType;
  value: number;
  capacity: number;
  metadata?: Record<string, unknown>;
}

/** Match phases used to drive realistic simulator patterns */
export type MatchPhase =
  | 'pre_match'
  | 'first_half'
  | 'halftime'
  | 'second_half'
  | 'post_match';

/** Anomaly scenarios that can be injected into the simulator */
export interface AnomalyScenario {
  id: string;
  name: string;
  description: string;
  triggerPhase: MatchPhase;
  triggerMinute: number;
  durationMinutes: number;
  affectedZones: string[];
  effects: AnomalyEffect[];
}

/** A single effect of an anomaly on a zone */
export interface AnomalyEffect {
  zone_id: string;
  type: TelemetryType;
  multiplier?: number;
  override?: number;
}

// ─── Zone & Stadium Types ───────────────────────────────────────────────────────

/** Zone types within the stadium */
export type ZoneType =
  | 'gate'
  | 'seating'
  | 'concourse'
  | 'concession'
  | 'restroom'
  | 'vip'
  | 'medical'
  | 'exit';

/** A zone within the stadium graph */
export interface StadiumZone {
  id: string;
  name: string;
  type: ZoneType;
  capacity: number;
  currentOccupancy: number;
  adjacentZones: string[];
  accessible: boolean;
  coordinates: { x: number; y: number };
  level: number;
}

/** Risk levels for zone capacity */
export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/** Current status of a zone, computed by the Crowd Intelligence Agent */
export interface ZoneStatus {
  zone_id: string;
  occupancyPercent: number;
  riskLevel: RiskLevel;
  trend: 'rising' | 'stable' | 'falling';
  etaToThreshold: number | null;
  lastUpdated: string;
}

// ─── Agent Types ────────────────────────────────────────────────────────────────

/** Agent identifiers */
export type AgentId =
  | 'fan-concierge'
  | 'crowd-intelligence'
  | 'ops-commander'
  | 'safety-accessibility';

/** A trace step in the agent reasoning pipeline */
export interface AgentTraceStep {
  id: string;
  timestamp: string;
  agentId: AgentId;
  action: string;
  input: string;
  output: string;
  durationMs: number;
  metadata?: Record<string, unknown>;
}

/** A complete agent trace spanning multiple steps */
export interface AgentTrace {
  traceId: string;
  steps: AgentTraceStep[];
  startTime: string;
  endTime?: string;
  triggerEvent?: string;
}

// ─── Crowd Intelligence Types ───────────────────────────────────────────────────

/** Structured event emitted by the Crowd Intelligence Agent */
export interface CrowdIntelEvent {
  id: string;
  timestamp: string;
  zone_id: string;
  riskLevel: RiskLevel;
  etaToThreshold: number;
  currentOccupancyPercent: number;
  trendDirection: 'rising' | 'stable' | 'falling';
  rateOfChange: number;
  recommendedAction: string;
  reasoning: string;
  isAnomaly: boolean;
}

// ─── Ops Commander Types ────────────────────────────────────────────────────────

/** Urgency levels for ops actions */
export type UrgencyLevel = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';

/** Staff response to an action card */
export type ActionResponse = 'accepted' | 'dismissed' | 'snoozed';

/** An action card generated by the Ops Commander Agent */
export interface ActionCard {
  id: string;
  timestamp: string;
  title: string;
  description: string;
  urgency: UrgencyLevel;
  triggeringSignals: TriggeringSignal[];
  recommendedAction: string;
  alternativeActions: string[];
  confidence: number;
  reasoning: string;
  status: 'pending' | ActionResponse;
  respondedAt?: string;
  respondedBy?: string;
  zoneId: string;
  agentTraceId?: string;
}

/** A signal that triggered an ops action */
export interface TriggeringSignal {
  source: string;
  metric: string;
  value: number;
  threshold: number;
  zone_id: string;
}

// ─── Chat Types ─────────────────────────────────────────────────────────────────

/** Supported languages */
export type Language = 'en' | 'es' | 'fr' | 'ar';

/** Accessibility modes for the fan concierge */
export type AccessibilityMode = 'standard' | 'simplified' | 'screen-reader';

/** A message in the fan concierge chat */
export interface ChatMessage {
  id: string;
  timestamp: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  language: Language;
  accessibilityMode: AccessibilityMode;
  metadata?: {
    ragSources?: string[];
    agentTraceId?: string;
    isEmergency?: boolean;
  };
}

/** Chat session state */
export interface ChatSession {
  sessionId: string;
  messages: ChatMessage[];
  language: Language;
  accessibilityMode: AccessibilityMode;
  createdAt: string;
  lastActivity: string;
}

// ─── Safety & Emergency Types ───────────────────────────────────────────────────

/** Emergency broadcast generated by the Safety Agent */
export interface EmergencyBroadcast {
  id: string;
  timestamp: string;
  type: 'evacuation' | 'shelter' | 'medical' | 'weather' | 'security';
  affectedZones: string[];
  messages: {
    language: Language;
    standard: string;
    simplified: string;
    screenReader: string;
  }[];
  severity: 'warning' | 'critical' | 'emergency';
  isActive: boolean;
}

// ─── Knowledge Base Types ───────────────────────────────────────────────────────

/** A chunk of knowledge base content for RAG retrieval */
export interface KnowledgeChunk {
  id: string;
  source: string;
  category: string;
  title: string;
  content: string;
  keywords: string[];
  language: Language;
}

/** RAG search result */
export interface RAGResult {
  chunk: KnowledgeChunk;
  score: number;
}

// ─── WebSocket Message Types ────────────────────────────────────────────────────

/** WebSocket message types for client-server communication */
export type WSMessageType =
  | 'simulator:telemetry'
  | 'simulator:phase'
  | 'agent:trace'
  | 'crowd:event'
  | 'ops:action'
  | 'ops:action_update'
  | 'chat:stream'
  | 'chat:complete'
  | 'broadcast:emergency'
  | 'zone:status'
  | 'client:subscribe'
  | 'client:chat'
  | 'client:emergency'
  | 'client:action_respond';

/** Generic WebSocket message wrapper */
export interface WSMessage<T = unknown> {
  type: WSMessageType;
  payload: T;
  timestamp: string;
}

// ─── Database Types ─────────────────────────────────────────────────────────────

/** Audit log entry for ops actions */
export interface AuditLogEntry {
  id: string;
  timestamp: string;
  actionCardId: string;
  staffRole: string;
  response: ActionResponse;
  notes?: string;
}

/** Stored chat message for persistence */
export interface StoredChatMessage {
  id: string;
  sessionId: string;
  role: string;
  content: string;
  language: string;
  accessibilityMode: string;
  timestamp: string;
}
